"""
Font assembly script – run with FontForge's bundled Python (ffpython).

  ffpython.exe fontforge_assemble.py <svg_dir> <output_ttf>

This script ONLY imports fontforge and has no external dependencies.
"""
import sys
import os
import glob

import fontforge

# Mode-specific character sets
_ALPHABET_CHARS = (
    [chr(c) for c in range(ord('A'), ord('Z') + 1)] +
    [chr(c) for c in range(ord('a'), ord('z') + 1)] +
    [chr(c) for c in range(ord('0'), ord('9') + 1)]
)

_SYMBOL_CHARS = [
    '`', '~', '!', '@', '#', '$', '%', '^',
    '&', '*', '(', ')', '-', '_', '+', '=',
    '[', ']', '{', '}', '|', '\\', ';', ':',
    "'", '"', ',', '.', '<', '>', '/', '?',
]


def _char_to_filename(char: str) -> str:
    """Convert a character to a unique filename, e.g. 'A' → 'U+0041.png'."""
    return f"U+{ord(char):04X}.png"


def _get_mode_chars(mode: str):
    """Return the character list for the given mode."""
    if mode == "alphabet":
        return _ALPHABET_CHARS
    if mode == "symbols":
        return _SYMBOL_CHARS
    raise ValueError(f"Unknown mode: {mode}")


def _scale_and_position_glyph(glyph, reference_height=None):
    """Scale glyph to ~70 % of em square and place it above baseline.

    If *reference_height* is provided, tiny glyphs are prevented from being
    blown up by capping the denominator at *reference_height*.
    """
    bbox = glyph.boundingBox()
    height = bbox[3] - bbox[1]
    if height <= 0:
        return
    target_height = glyph.font.em * 0.7
    if reference_height and reference_height > 0:
        scale = target_height / max(height, reference_height)
    else:
        scale = target_height / height
    glyph.transform((scale, 0, 0, scale, 0, 0))
    bbox = glyph.boundingBox()
    x_shift = 50
    y_shift = (glyph.font.em * 0.15) - bbox[1]
    glyph.transform((1, 0, 0, 1, x_shift, y_shift))


def _set_glyph_spacing(glyph, left=30, right=30):
    """Set side bearings from outline width."""
    bbox = glyph.boundingBox()
    outline_width = bbox[2] - bbox[0]
    glyph.width = int(outline_width + left + right)
    glyph.left_side_bearing = left
    glyph.right_side_bearing = right


def build_ttf(svg_dir: str, output_path: str, mode: str = "alphabet"):
    """Assemble pre-traced SVGs into a TrueType font."""
    characters = _get_mode_chars(mode)
    char_map = {c: ord(c) for c in characters}
    missing = []
    processed = 0

    font = fontforge.font()
    font.fontname = "MyHandwriting"
    font.fullname = "My Handwriting"
    font.familyname = "MyHandwriting"
    font.version = "001.000"
    font.copyright = "Generated by handwriting-font pipeline"
    font.encoding = "UnicodeFull"
    font.em = 1000

    # ---- First pass: import all glyphs and collect heights ----
    glyph_map = {}
    heights = []
    for char in characters:
        svg_name = _char_to_filename(char).replace('.png', '.svg')
        svg_path = os.path.join(svg_dir, svg_name)
        if not os.path.exists(svg_path):
            missing.append(char)
            print(f"  [skip] {svg_name} not found")
            continue

        try:
            codepoint = char_map[char]
            glyph = font.createChar(codepoint)
            glyph.importOutlines(svg_path)
            glyph.removeOverlap()
            glyph_map[char] = glyph
            bbox = glyph.boundingBox()
            h = bbox[3] - bbox[1]
            if h > 0:
                heights.append(h)
            print(f"  [ok]   {char}  ->  U+{codepoint:04X}")
        except Exception as exc:
            print(f"  [err]  {char}: {exc}")
            missing.append(char)

    processed = len(glyph_map)
    if processed == 0:
        raise RuntimeError("No glyphs were successfully processed; aborting.")

    # Compute reference height from 75th percentile so tiny glyphs
    # (period, comma, quotes) aren't blown up to full cap-height.
    if heights:
        heights_sorted = sorted(heights)
        reference_height = heights_sorted[int(len(heights_sorted) * 0.75)]
    else:
        reference_height = None

    # ---- Second pass: scale and set spacing consistently ----
    for char, glyph in glyph_map.items():
        _scale_and_position_glyph(glyph, reference_height=reference_height)
        _set_glyph_spacing(glyph, left=30, right=30)

    # Add space character so words don't show missing-glyph boxes
    space = font.createChar(0x0020)
    space.width = int(font.em * 0.25)

    font.generate(output_path, flags=("opentype",))
    print(f"\nSuccess: generated '{output_path}' with {processed} glyphs.")
    if missing:
        print(f"Missing characters ({len(missing)}): {', '.join(missing)}")

    return processed, missing


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: ffpython.exe fontforge_assemble.py <svg_dir> <output_ttf> [mode]")
        sys.exit(1)

    svg_dir = sys.argv[1]
    output_path = sys.argv[2]
    mode = sys.argv[3] if len(sys.argv) > 3 else "alphabet"
    build_ttf(svg_dir, output_path, mode=mode)
